apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: myapp
  labels:
    app: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
    tier: web
  ports:
    - name: http
      port: 80
      targetPort: 8080
